backend: { name: git-gateway, branch: master }
locale: 'es'
media_folder: '_static/images'
collections:
  - name: files
    label: Configuracion
    editor: { preview: false }
    files:
      - label: Playlists
        name: playlists
        file: _data/playlists.json
        media_folder: '_static/images/playlists'
        fields:
          - label: Playlists
            name: playlists
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Imagen, name: image, widget: image }
