backend: { name: git-gateway, branch: main }
local_backend: true
locale: 'es'
media_folder: 'static/images/uploads'
collections:
  - label: Configuracion
    name: files
    editor: { preview: false }
    files:
      - label: "Settings"
        name: "settings"
        file: "_data/settings.json"
        fields:
          - { label: URL, name: url, widget: string }
          - { label: Titulo, name: title, widget: string }
          - { label: Descripcion, name: description, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: "Open Graph", name: image, widget: string }
          - { label: "Radio URL", name: radio, widget: string }
          - { label: "Google Play", name: google-play, widget: string }
          - { label: Youtube, name: youtube, widget: string }
          - { label: Facebook, name: facebook, widget: string }
          - { label: Instagram, name: instagram, widget: string }
          - { label: Spotify, name: spotify, widget: string }
          - { label: E-Mail, name: email, widget: string }
      - label: Playlists
        name: playlists
        file: _data/playlists.json
        fields:
          - label: Playlists
            name: playlists
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Imagen, name: imagen, widget: image }
      - label: Programación
        name: programacion
        file: _data/programacion.json
        fields:
          - label: Programación
            name: programacion
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - label: Episodios
                name: episodios
                widget: list
                fields:
                  - { label: Titulo, name: title, widget: string }
                  - { label: URL, name: url, widget: string }
                  - { label: Fecha, name: fecha, widget: datetime, format: "DD-MM-YYYY", date_format: "DD-MM-YYYY", time_format: false }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Dia, name: dia, widget: string }
              - { label: Horario, name: hora, widget: string }
              - { label: Tags, name: tags, widget: list }
              - { label: Descripcion, name: descripcion, widget: "markdown" }
              - { label: Musicalizacion, name: musicalizacion, widget: string }
              - { label: Contacto, name: contacto, widget: string }
      - label: Editorial
        name: editorial
        file: _data/editorial.json
        fields:
          - label: Editorial
            name: editorial
            widget: list
            allow_add: true
            fields:
              - { label: Titulo, name: titulo, widget: string }
              - { label: Imagen, name: imagen, widget: image }
              - { label: Precio, name: precio, widget: number }
              - { label: URL, name: url, widget: string }
              - { label: Descripcion, name: descripcion, widget: "markdown" }
              - { label: Autor, name: autor, widget: string }
              - { label: Instagram, name: instagram, widget: string }
  - label: Noticias
    name: noticias
    folder: _pages/p
    create: true
    editor: { preview: false }
    summary: '{{day}}/{{month}}/{{year}} {{hour}}:{{minute}} - {{fields.title}}'
    # identifier_field: date
    slug: '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}'
    # slug: '{{year}}{{month}}{{day}}-{{slug}}'
    fields:
      - { label: Titulo, name: title, widget: string }
      - { label: Fecha, name: date, widget: datetime }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["noticias", "fanzines", "eventos", "encuentros", "talleres"]
      - { label: "Texto", name: "body", widget: "markdown" }
